#!/bin/bash

# NOTE: Ubuntu 16.04 not fully supporting python3

export DEBIAN_FRONTEND=noninteractive

# install python setuptools
apt-get update -q
apt-get install -qy --no-install-recommends python-setuptools
apt-get -y install python3-pip
apt-get clean
rm -rf /var/lib/apt/lists/*


# install dependencies (in requirements.txt)
pip3 install -r requirements.txt

